### ISSUE TITLE
Man kan som kunde kigger på andre kunders order, ved at indstaste istedet for deres nummer i URL

### ISSUE THREAD

**Issue by mrPrimeBeef** [mrPrimeBeef/FogCarport#33]
Der mangler at blive lavet en guard condition omkring det skal være logget ind kunde som har adgang, det skal laves i account controller -> showCustomerOrderPage

**Comment by pbollhorn** [comment]
Issue is solved now:
Added an extra guard condition to AccountController.showCustomerOrderPage() so a customer only has access to see his own orders
